metadata description = 'Bicep template for Aerulias AI deployment to Azure'

@minLength(1)
@maxLength(64)
@description('Name of the environment')
param environmentName string

@minLength(1)
@description('Primary location for all resources')
param location string

@description('The resource token generated by azd')
param resourceToken string

@description('Whether to enable Application Insights')
param enableAppInsights bool = true

// Generate resource names
var resourceGroupName = 'rg-aerulias-${environmentName}-${resourceToken}'
var appServicePlanName = 'plan-aerulias-${environmentName}-${resourceToken}'
var appServiceName = 'app-aerulias-${environmentName}-${resourceToken}'
var keyVaultName = 'kv-aerulias-${resourceToken}'
var appInsightsName = 'ai-aerulias-${environmentName}-${resourceToken}'
var storageAccountName = 'staerulias${resourceToken}'

// Variables
var pythonVersion = '3.11'
var skuName = 'B2'
var skuTier = 'Basic'

// Configure CORS origins
var corsOrigins = [
  'http://localhost:3000'
  'http://localhost:8000'
  'http://127.0.0.1:3000'
  'http://127.0.0.1:8000'
]

// ===== Resource Group =====
resource resourceGroup 'Microsoft.Resources/resourceGroups@2021-04-01' = {
  name: resourceGroupName
  location: location
}

// ===== App Service Plan =====
resource appServicePlan 'Microsoft.Web/serverfarms@2021-02-01' = {
  name: appServicePlanName
  location: location
  kind: 'linux'
  sku: {
    name: skuName
    tier: skuTier
  }
  properties: {
    reserved: true
  }
}

// ===== Key Vault =====
resource keyVault 'Microsoft.KeyVault/vaults@2021-06-01-preview' = {
  name: keyVaultName
  location: location
  properties: {
    enabledForDeployment: true
    enabledForTemplateDeployment: true
    enabledForDiskEncryption: false
    tenantId: subscription().tenantId
    sku: {
      family: 'A'
      name: 'standard'
    }
    accessPolicies: []
  }
}

// ===== Application Insights =====
resource appInsights 'Microsoft.Insights/components@2020-02-02' = if (enableAppInsights) {
  name: appInsightsName
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    RetentionInDays: 30
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
  }
}

// ===== Storage Account (for file persistence) =====
resource storageAccount 'Microsoft.Storage/storageAccounts@2021-06-01' = {
  name: storageAccountName
  location: location
  kind: 'StorageV2'
  sku: {
    name: 'Standard_LRS'
  }
  properties: {
    accessTier: 'Hot'
    minimumTlsVersion: 'TLS1_2'
    supportsHttpsTrafficOnly: true
  }
}

// ===== App Service (with Managed Identity) =====
resource appService 'Microsoft.Web/sites@2021-02-01' = {
  name: appServiceName
  location: location
  kind: 'app,linux'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    serverFarmId: appServicePlan.id
    siteConfig: {
      linuxFxVersion: 'PYTHON|${pythonVersion}'
      alwaysOn: true
      http20Enabled: true
      minTlsVersion: '1.2'
      scmMinTlsVersion: '1.2'
      appSettings: [
        {
          name: 'WEBSITES_ENABLE_APP_SERVICE_STORAGE'
          value: 'true'
        }
        {
          name: 'WEBSITE_PYTHON_VERSION'
          value: pythonVersion
        }
        {
          name: 'ENABLE_ORYX_BUILD'
          value: 'true'
        }
        {
          name: 'OPENROUTER_API_KEY'
          value: '@Microsoft.KeyVault(SecretUri=${keyVault.properties.vaultUri}secrets/openrouter-api-key/)'
        }
        {
          name: 'OPENROUTER_BASE_URL'
          value: 'https://openrouter.ai/api/v1'
        }
        {
          name: 'OPENROUTER_MODEL'
          value: 'openai/gpt-4o-mini'
        }
        {
          name: 'OPENROUTER_SITE_URL'
          value: 'https://${appService.properties.defaultHostName}'
        }
        {
          name: 'OPENROUTER_APP_NAME'
          value: 'aerulias_ai'
        }
        {
          name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
          value: enableAppInsights ? appInsights.properties.ConnectionString : ''
        }
      ]
      corsSettings: {
        allowedOrigins: corsOrigins
        supportCredentials: false
      }
    }
  }
}

// ===== Key Vault Access Policy for App Service =====
resource keyVaultAccessPolicy 'Microsoft.KeyVault/vaults/accessPolicies@2021-06-01-preview' = {
  name: '${keyVault.name}/add'
  properties: {
    accessPolicies: [
      {
        tenantId: subscription().tenantId
        objectId: appService.identity.principalId
        permissions: {
          secrets: [
            'get'
            'list'
          ]
        }
      }
    ]
  }
}

// ===== Outputs =====
@description('The name of the created App Service')
output appServiceName string = appService.name

@description('The default hostname of the App Service')
output appServiceUrl string = 'https://${appService.properties.defaultHostName}'

@description('The name of the Key Vault')
output keyVaultName string = keyVault.name

@description('The name of Application Insights')
output appInsightsName string = enableAppInsights ? appInsights.name : ''

@description('The Application Insights instrumentation key')
output appInsightsInstrumentationKey string = enableAppInsights ? appInsights.properties.InstrumentationKey : ''

@description('The App Service resource ID')
output appServiceResourceId string = appService.id
